import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Footer1 from "@/components/Footer1";
import Navbar from "@/components/Header1";
import { ArrProvider } from "@/utils/Arrcontext";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dine Market",
  description: "Generated by Muhammad Saad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const valuesArr=[];  
  return (
    <html lang="en">
      <body className={`${inter.className}  `}>
        <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
          <ArrProvider>
          <div className="box-border">
            <Navbar />
            {children}
            <Footer />
          </div>
          <Footer1 />
          </ArrProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
